BEGIN TRY

BEGIN TRAN;

-- CreateTable
CREATE TABLE [dbo].[Products] (
    [ProductID] INT NOT NULL IDENTITY(1,1),
    [ProductName] VARCHAR(255) NOT NULL,
    [Description] VARCHAR(max),
    [Price] DECIMAL(10,2) NOT NULL,
    [StockQuantity] INT CONSTRAINT [DF__Products__StockQ__49C3F6B7] DEFAULT 0,
    [CreatedAt] DATETIME CONSTRAINT [DF__Products__Create__4AB81AF0] DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT [PK__Products__B40CC6EDE717DB68] PRIMARY KEY CLUSTERED ([ProductID])
);

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
